# Numpy Array 만들기

- array()

In [1]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
li = [1, 2, 3]
print(li)
print(type(li))

[1, 2, 3]
<class 'list'>


In [3]:
import numpy as np
li = [1, 2, 3]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3]
[1 2 3]


In [4]:
import numpy as np
li = [[1, 2, 3], [4 , 5, 6]]
arr = np.array(li)
print(li)
print(arr)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


- arrange()

In [5]:
import numpy as np 
arr_1 = np.arange(1, 10, 3)
arr_2 = np.arange(1, 10)
arr_3 = np.arange(10)
print(arr_1)
print(arr_2)
print(arr_3)

[1 4 7]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
a_1 = list(range(1, 10, 3))
a_2 = list(range(1, 10))
a_3 = list(range(10))
print(a_1)
print(a_2)
print(a_3)

[1, 4, 7]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


- linspace()

In [7]:
import numpy as np 
arr_1 = np.linspace(1, 10, 2)
arr_2 = np.linspace(1, 10, 5)
arr_3 = np.linspace(1, 10)
print(arr_1)
print(arr_2)
print(arr_3)
print(arr_3.size)

[ 1. 10.]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
50


- 모양(shape), 차원(dimension), 크기(size) 확인

In [8]:
import numpy as np 
arr = np.linspace(1, 10, 2)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1. 10.]
(2,)
1
2


In [9]:
import numpy as np
li = [[1, 2, 3], [4 , 5, 6]]
arr = np.array(li)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


- 모양 재구성(reshape)

In [10]:
import numpy as np 
a = np.arange(10)
b = a.reshape(2, 5)
c = b.reshape(5,2)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
import numpy as np 
a = np.arange(10)
b = np.reshape(3, 3)

ValueError: cannot reshape array of size 1 into shape (3,)

- zeros()
- ones()

In [12]:
import numpy as np 
a = np.zeros(10)
b = np.zeros((2,4))
c = np.ones(5)
d = np.ones((3, 2))
print(a)
print(b)
print(c)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
import numpy as np 
a = np.zeros(10, dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


- indexing
- slicing

In [14]:
import numpy as np 
data = np.array([1, 2, 3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [15]:
import numpy as np 
data = np.array([1, 2, 3])
a = data[1]
print(a, type(a))
b = data[1:2]
print(b, type(b))

2 <class 'numpy.int32'>
[2] <class 'numpy.ndarray'>


In [16]:
import numpy as np 
a = np.arange(12)
b = a.reshape(3, 4)
print(b)
print(b[1:3, 2:])

print(b[0:2, 1:3])  #Quiz, 클래스룸 비공개 댓글로 남겨주세요.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 6  7]
 [10 11]]
[[1 2]
 [5 6]]
