# Numpy 연산

Vector(1차원의 Numpy array) 연산

In [1]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)

print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [2]:
print(a+b)

[20 31 42 53]


In [3]:
print(a*b)

[  0  30  80 150]


In [4]:
print(a*2)

[ 40  60  80 100]


In [5]:
print(b**2)

[0 1 4 9]


element wise
![elementwise1](https://numpy.org/devdocs/_images/np_sub_mult_divide.png)
![elementwise2](https://numpy.org/devdocs/_images/np_matrix_arithmetic.png)

broadcast
![broadcast](https://numpy.org/devdocs/_images/np_multiply_broadcasting.png)

Matrix(2차원의 Numpy array) 연산

In [6]:
import numpy as np
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [7]:
print(A+B)

[[3 1]
 [3 5]]


In [8]:
print(A*B)  

[[2 0]
 [0 4]]


In [9]:
print(np.dot(A, B))  #matrix product, dot product

[[5 4]
 [3 4]]


In [10]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [11]:
print(a*b)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [12]:
print(np.dot(a, b))

[[ 58  64]
 [139 154]]


수학 함수

In [13]:
import numpy as np
a = np.arange(1,11).reshape(2,-1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
print(np.sum(a))

55


In [15]:
print(np.mean(a))  #평균
print(np.std(a))  #표준편차
print(np.median(a))  #중앙값
print(np.var(a))  #분산
print(np.max(a), np.min(a))  #최댓값, 최솟값
print(np.percentile(a, 25))  #1사분위 수
print(np.percentile(a, 50))  #2사분위 수=중앙값
print(np.percentile(a, 75)) # 3사분위 수

5.5
2.8722813232690143
5.5
8.25
10 1
3.25
5.5
7.75


![cal](https://numpy.org/devdocs/_images/np_aggregation.png)

axis


In [16]:
import numpy as np
a = np.arange(1,11)
print(a)
print(np.sum(a))
print(np.sum(a, axis=0))

[ 1  2  3  4  5  6  7  8  9 10]
55
55


In [17]:
print(np.sum(a,axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [18]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
print(a)
print(np.sum(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78


In [19]:
print(np.sum(a, axis=0))

[15 18 21 24]


In [20]:
print(np.sum(a, axis=1))

[10 26 42]


In [21]:
print(np.sum(a, axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [22]:
print(np.max(a, axis=0))

[ 9 10 11 12]


![axis1](array-axis2.png)
![axis1](axis.jpg)

# 관절염 환자 데이터 분석

In [23]:
import numpy as np
data = np.loadtxt('inflammation.csv', delimiter=',')

1. data 배열 출력

2. 상위 5행 출력

3. 마지막 행 출력

4. data 배열 모양 출력

5. data 배열의 모든 값의 평균, 분산, 표준편차

6. 첫번째 환자의 염증수치 평균, 최댓값, 최솟값

7. 둘째날 모든 환자의 염증수치 평균

8. 각 환자의 염증수치 평균

9. 각 환자의 염증수치 최대값